### PR TITLE
fix(build options): wrong output

### PR DESCRIPTION
**Pull request by 2234839**

### CODE REVIEW

**Comment by alias-mac** [comment]
Can you expand on what you are trying to do here?

When I use commonJS with:
```js
const mongodbQueue = require('@openwar/mongodb-queue');
```

`mongodbQueue` is the function that I expose. I want to enforce that only this is exposed and nothing else will.
The reason why I don't want named exports is due to interoperability with other tools (like babel).
See more in the [rollup issue thread](https://github.com/rollup/rollup/issues/1961#issuecomment-423037881).

If you can provide a reproducible issue using https://codesandbox.io/ would be great. Thanks!

**Comment by 2234839** [comment]
> 
> 
> Can you expand on what you are trying to do here?
> 
> When I use commonJS with:
> 
> ```js
> const mongodbQueue = require('@openwar/mongodb-queue');
> ```
> 
> `mongodbQueue` is the function that I expose. I want to enforce that only this is exposed and nothing else will.
> The reason why I don't want named exports is due to interoperability with other tools (like babel).
> See more in the [rollup issue thread](https://github.com/rollup/rollup/issues/1961#issuecomment-423037881).
> 
> If you can provide a reproducible issue using https://codesandbox.io/ would be great. Thanks!


I am trying to solve the problem shown below, according to my attempt to use `named` the compiled code will not become undefined here

图片

https://codesandbox.io/s/wonderful-kirch-hb4j3?file=/src/app.controller.ts

**Comment by alias-mac** [comment]
Thanks @2234839! This is a [known issue due to nodejs imports vs es6 imports](https://www.typescriptlang.org/tsconfig#esModuleInterop) (with other tools).

When consuming it using vanilla nodejs (no other tools or transpilers) it works well as you saw, but becomes a problem when you ask tools typescript or tools that expect es6 syntax.

A quick fix for the code sample you provided would be to do:
```js
import * as mongoDbQueue from '@openwar/mongodb-queue';
```

But a better fix is to enable `esModuleInterop` in your typescript config, like:
```json
{
  "compilerOptions": {
    // other options you have already
    "esModuleInterop": true
  }
}
```
This is a known issue with other libraries too:
https://stackoverflow.com/questions/56238356/understanding-esmoduleinterop-in-tsconfig-file

I don't want to sacrifice the easy of use in vanilla nodejs by adding named exports because with this change normal nodejs users would have to write code like:
```js
const mongoDbQueue = require('@openwar/mongodb-queue').default;
```
(notice the `default` at the end of `require`), which is quite ugly and not expected for regular consumers of libraries for nodejs.
The problem is really that typescript and they assume that in the docs:
> By default (with esModuleInterop false or not set) TypeScript treats CommonJS/AMD/UMD modules similar to ES6 modules. In doing this, there are two parts in particular which turned out to be flawed assumptions:

This is what is causing the problem for you, but setting that flag to true it will work as expected.

Another option would be for you to consume the module as provided in the package.json:
https://github.com/openwar/mongodb-queue/blob/9433222808fbf66ceee9c5f994edbdfa68fce04e/package.json#L6-L7

I know that not all tools are ready for that and it will depend on case by case. This library is ready to be consumed as esm tho.

**Comment by 2234839** [comment]
Thanks a lot @alias-mac. Configuring tsconfig `"esModuleInterop": true` solved my problem perfectly

**Pull request closed without merging**
